### ISSUE TITLE
Can you take this down?

### ISSUE THREAD

**Issue by CortexPE** [BajanVlogs/Bosses#5]
Unless you want legal shit and drama between us, Take this repo down.

You even forgot to change the namespace...
Even if you've removed the Copyright headers, I still hold the copyright to the files here...

And stop putting up the plugins you bought on public as if you made them... Its a crime called plagiarism.

How do you even expect me to help you fix the "Server Selector" plugin now that this is your third time on putting my plugins public?

**Comment by TheAz928** [comment]
True
